site_name: USTC OSH 2024 课程主页
repo_name: OSH-2024/OSH-2024.github.io
repo_url: https://github.com/OSH-2024/OSH-2024.github.io
theme:
  name: material
  language: zh
  features:
    - content.code.copy
    - navigation.footer
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - mdx_truly_sane_lists
  - toc:
      permalink: true
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
extra_css:
  # Borrow CSS from Linux 101 still
  - 'https://101.ustclug.org/css/extra.css'
nav:
  - 首页: README.md
  - 实验零:
      - 零：简介: lab0/README.md
      - 一：Linux: lab0/linux.md
      - 二：Git: lab0/git.md
      - 三：Markdown: lab0/markdown.md
      - 四：Makefile: lab0/makefile.md
      - 五：编程说明: lab0/programming.md
  - 实验一:
      - 零：简介: lab1/README.md
      - 一：Linux 编译: lab1/phase1.md
      - 二：创建初始内存盘: lab1/phase2.md
      - 三：添加自定义系统调用: lab1/phase3.md

  - FAQ: faq/README.md
extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
